version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: project-management-app
        container_name: project_management_app
        ports:
            - "8000:9000"
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
